"""schema inicial

Revision ID: 4a326e2f07a9
Revises:
Create Date: 2026-09-01 19:23:57.573589
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '4a326e2f07a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'event_date', name='uq_earnings_event')
    )
    with op.batch_alter_table('earnings_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_earnings_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_earnings_events_symbol'), ['symbol'], unique=False)

    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('actual', sa.String(length=64), nullable=False),
    sa.Column('forecast', sa.String(length=64), nullable=False),
    sa.Column('previous', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_name', 'country', 'event_date', name='uq_economic_event')
    )
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_events_event_date'), ['event_date'], unique=False)

    op.create_table('global_news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_news_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_news_items_impact_score'), ['impact_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_news_items_url'), ['url'], unique=True)

    op.create_table('lms_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_courses_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_courses_slug'), ['slug'], unique=True)

    op.create_table('lms_live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'ENDED', name='livestatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stream_url', sa.String(length=1024), nullable=False),
    sa.Column('replay_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_live_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_live_sessions_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_live_sessions_status'), ['status'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    op.create_table('macro_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_snapshots_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_snapshots_taken_at'), ['taken_at'], unique=False)

    op.create_table('morning_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('delivered_telegram', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('morning_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_morning_reports_generated_at'), ['generated_at'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_url'), ['url'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('decision_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(length=512), nullable=False),
    sa.Column('invalidation', sa.String(length=512), nullable=False),
    sa.Column('timeframe', sa.String(length=64), nullable=False),
    sa.Column('risk_notes', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_journals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_journals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_journals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_journals_user_id'), ['user_id'], unique=False)

    op.create_table('lms_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_modules_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_modules_order'), ['order'], unique=False)

    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('rule_preset', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('saas_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('brand_name', sa.String(length=96), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ADVISOR', name='subscriptionplan'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saas_workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saas_workspaces_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='transactionside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_telegram', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_logs_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_logs_triggered_at'), ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('client_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_segments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('lms_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=1024), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['lms_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_lessons_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_lessons_order'), ['order'], unique=False)

    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.Enum('TELEGRAM', 'EMAIL', 'WEBHOOK', name='notificationchanneltype'), nullable=False),
    sa.Column('destination', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('recommendation_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('suggested_size_pct', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('fair_reason', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('memory_json', sa.Text(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('prediction_json', sa.Text(), nullable=False),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_status', sa.String(length=32), nullable=False),
    sa.Column('outcome_return_1d_pct', sa.Float(), nullable=True),
    sa.Column('outcome_return_5d_pct', sa.Float(), nullable=True),
    sa.Column('outcome_return_20d_pct', sa.Float(), nullable=True),
    sa.Column('outcome_1d_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_20d_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_outcome_status'), ['outcome_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_regime'), ['regime'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('audience', sa.String(length=96), nullable=False),
    sa.Column('include_ai_summary', sa.Boolean(), nullable=False),
    sa.Column('include_backtest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_share_links_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('technical_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=96), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_levels_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_levels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_levels_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_levels_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_levels_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('trade_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_setups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_setups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_setups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_setups_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_setups_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_setups_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['saas_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('logic', sa.Enum('ALL', 'ANY', name='rulelogic'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lms_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lesson_progress_user_lesson')
    )
    with op.batch_alter_table('lms_lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_lesson_progress_user_id'), ['user_id'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_taken_at'), ['taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_watchlist_item_id'), ['watchlist_item_id'], unique=False)

    op.create_table('alert_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('PRICE_ABOVE', 'PRICE_BELOW', 'PCT_CHANGE', 'RSI_OVERBOUGHT', 'RSI_OVERSOLD', 'MA_CROSS_UP', 'MA_CROSS_DOWN', 'MACD_CROSS_UP', 'MACD_CROSS_DOWN', 'VOLUME_SPIKE', name='ruletype'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('param_a', sa.Integer(), nullable=False),
    sa.Column('param_b', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_conditions')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_snapshots_watchlist_item_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_taken_at'))

    op.drop_table('price_snapshots')
    with op.batch_alter_table('lms_lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_lesson_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_lms_lesson_progress_lesson_id'))

    op.drop_table('lms_lesson_progress')
    op.drop_table('alert_rules')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_symbol'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('trade_setups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_setups_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_trade_setups_user_id'))
        batch_op.drop_index(batch_op.f('ix_trade_setups_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_setups_status'))
        batch_op.drop_index(batch_op.f('ix_trade_setups_created_at'))

    op.drop_table('trade_setups')
    with op.batch_alter_table('technical_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_levels_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_technical_levels_user_id'))
        batch_op.drop_index(batch_op.f('ix_technical_levels_symbol'))
        batch_op.drop_index(batch_op.f('ix_technical_levels_created_at'))
        batch_op.drop_index(batch_op.f('ix_technical_levels_active'))

    op.drop_table('technical_levels')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_share_links_slug'))

    op.drop_table('share_links')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_workspace_id'))

    op.drop_table('report_templates')
    with op.batch_alter_table('recommendation_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_symbol'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_regime'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_outcome_status'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_action'))

    op.drop_table('recommendation_decisions')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_workspace_id'))

    op.drop_table('notification_channels')
    with op.batch_alter_table('lms_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_lessons_order'))
        batch_op.drop_index(batch_op.f('ix_lms_lessons_module_id'))

    op.drop_table('lms_lessons')
    with op.batch_alter_table('client_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_segments_workspace_id'))

    op.drop_table('client_segments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alert_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_alert_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_logs_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alert_logs_symbol'))

    op.drop_table('alert_logs')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_symbol'))
        batch_op.drop_index(batch_op.f('ix_transactions_executed_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('saas_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saas_workspaces_user_id'))

    op.drop_table('saas_workspaces')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_user_id'))

    op.drop_table('playbooks')
    with op.batch_alter_table('lms_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_modules_order'))
        batch_op.drop_index(batch_op.f('ix_lms_modules_course_id'))

    op.drop_table('lms_modules')
    with op.batch_alter_table('decision_journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_journals_user_id'))
        batch_op.drop_index(batch_op.f('ix_decision_journals_symbol'))
        batch_op.drop_index(batch_op.f('ix_decision_journals_status'))
        batch_op.drop_index(batch_op.f('ix_decision_journals_created_at'))

    op.drop_table('decision_journals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_url'))
        batch_op.drop_index(batch_op.f('ix_news_items_symbol'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))

    op.drop_table('news_items')
    with op.batch_alter_table('morning_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_morning_reports_generated_at'))

    op.drop_table('morning_reports')
    with op.batch_alter_table('macro_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_snapshots_taken_at'))
        batch_op.drop_index(batch_op.f('ix_macro_snapshots_key'))

    op.drop_table('macro_snapshots')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_attempted_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('lms_live_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_live_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_lms_live_sessions_scheduled_at'))

    op.drop_table('lms_live_sessions')
    with op.batch_alter_table('lms_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_courses_slug'))
        batch_op.drop_index(batch_op.f('ix_lms_courses_order'))

    op.drop_table('lms_courses')
    with op.batch_alter_table('global_news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_news_items_url'))
        batch_op.drop_index(batch_op.f('ix_global_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_global_news_items_impact_score'))
        batch_op.drop_index(batch_op.f('ix_global_news_items_category'))

    op.drop_table('global_news_items')
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_events_event_date'))

    op.drop_table('economic_events')
    with op.batch_alter_table('earnings_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earnings_events_symbol'))
        batch_op.drop_index(batch_op.f('ix_earnings_events_event_date'))

    op.drop_table('earnings_events')
    # ### end Alembic commands ###
